### ISSUE TITLE
Search showing no results

### ISSUE THREAD

**Issue by Beerisforwinners** [structurizr/cloud#1]
Currently looking at Cloud Service and Slack integration, search doesn't appear to be returning results for any searches:

![image](https://user-images.githubusercontent.com/38894002/190590357-f9fd16bb-3574-4be4-9191-1dcc6d35daac.png)

**Comment by simonbrowndotje** [comment]
It's hard to say what's happening without more information, but free workspaces are not indexed for search, so if you've recently activated a trial or started a subscription, you'll need to save your workspace (e.g. push via the API, edit a diagram and save the workspace, etc) to enable indexing.

**Comment by Beerisforwinners** [comment]
That's it - edited and saved, serach now working as expected. Thanks Simon
