### ISSUE TITLE
MarkDown documentation creation

### ISSUE THREAD

**Issue by KKorzuno** [structurizr/cloud#10]
I generate Markdown and what I get in the "documentation" page of the website is different than what I get in the structurizr.com/help/documentation tester.
1. The second ## line is completely ignored in the cloud service documentation webpage and I get this: 
![image](https://user-images.githubusercontent.com/1334346/217076100-d3f84c87-4a50-4bdd-98eb-32ecbbcc9053.png)

2. Also, for a reason not apparent to me, the webpage adds numbers (1.) to items having ## and (1.1) to the items having ###. 
This is the Markdown:
(I deleted some lines that should not have any impact in the example that I pasted, just to be clear)

### GoogleFormsCLIAPI
- Payroll Info to Monday Task

### Deactivate User
- Exit Interview
### Manager/Team Lead Report
- Manager/Team Lead Report to HR Tasks Monday Board

**Comment by simonbrowndotje** [comment]
I'm not sure if you saw [Structurizr - Documentation - Headings and sections](https://structurizr.com/help/documentation/headings) (it's linked to from the top of structurizr.com/help/documentation) but I've updated it to make it clearer what's happening here. There's also an example linked from that page.

I've also removed those rendering testers, as they are not indicative of the end-result with regards to section numbering.

**Comment by simonbrowndotje** [comment]
> The second ## line is completely ignored in the cloud service documentation webpage

The cloud service is expecting that each Markdown file only contains a single `##` heading ... i.e. one top-level section per file. See the following for more information:
- https://github.com/structurizr/documentation/blob/main/src/main/java/com/structurizr/documentation/importer/DefaultDocumentationImporter.java
- https://github.com/structurizr/dsl/blob/master/docs/language-reference.md#documentation

**Comment by KKorzuno** [comment]
Thanks. It is easier to understand what is going on after the update you made, but I would put info that a page is expected to have only one ## heading. That part is not clear even after the update.

**Comment by simonbrowndotje** [comment]
There are some code changes being made while Structurizr is being open sourced, and this restriction will disappear.

**Comment by simonbrowndotje** [comment]
Build 2931 of Structurizr Lite includes the new documentation handling code if you'd like to try it. To use Lite with the Java library, you can follow the guide at https://structurizr.com/share/76352/documentation#code-based-client-library
