### ISSUE TITLE
Notion integration

### ISSUE THREAD

**Issue by fabiocarneiro** [structurizr/cloud#11]
### Description

Is it possible to develop a [https://www.notion.so/product](url) integration? Notion is very popular and will most likely replace confluence as market leader if it didn't do that yet.

Here is some documentation on how that could be done
https://developers.notion.com/docs/build-a-link-preview-integration

Another possibility would be using oEmbed, but then you run into token permission issues.

### Priority

High

### Resolution

I have no budget, please add this feature for free

**Comment by simonbrowndotje** [comment]
Structurizr has supported oEmbed for a while now ([e.g. via Embed.ly](https://embed.ly/provider/structurizr)), but for some reason Notion doesn't discover this is possible. There is a workaround though, which is to craft up an embed URL yourself in the following format:

```
https://structurizr.com/embed/{workspaceId}/{sharingToken}?diagram={viewKey}
```

For example:

```
https://structurizr.com/embed/39257/be64ff75-1dd8-44ce-8e22-a51f406a5b53?diagram=SystemContext
```

If you embed the above URL in a Notion page, it should embed the specified diagram.

<img width="1728" alt="Screenshot 2023-05-04 at 10 18 13" src="https://user-images.githubusercontent.com/1009874/236162614-93124718-3d18-4260-8b46-fd34d5df634e.png">

**Comment by fabiocarneiro** [comment]
@simonbrowndotje Can you make this a little bit more convenient? Its not really feasible to explain everyone in the organization how to create this URL. If it could be generated from the diagram viewer it would be a lot easier.

**Comment by fabiocarneiro** [comment]
It was also not immediately obvious to me that I had to enable the Workspace Sharing. It would also be better if the sharing tokens would be created per-diagram and could be revoked.

**Comment by simonbrowndotje** [comment]
Notion integration is now available -> https://structurizr.com/help/notion

(it turns out that although the oEmbed discovery functionality was in place, I needed to "register" Structurizr with the iframely service, which Notion seems to use behind the scenes)
