### ISSUE TITLE
Sort order is not consistent with the documentation

### ISSUE THREAD

**Issue by JasonBSteele** [structurizr/cloud#16]
### Description

I have just used Structalizr cloud to create a few simple diagrams and expected the order of the diagrams to be topmost first. The documentation backs this up.  See Diagram Sorting here: https://structurizr.com/help/diagrams where it lists:

**Diagram sorting**
By default, diagrams are first sorted by scope (unscoped, followed by software systems by name), and then by diagram type, as follows:

- Unscoped diagrams
  - System landscape diagrams
  - Dynamic diagrams
  - Deployment diagrams
- Software system 1
  - System context diagrams
  - Container context diagrams
  - Component context diagrams
  - Dynamic diagrams
  - Deployment diagrams
- Software system 2
  - System context diagrams
  - Container context diagrams
  - Component context diagrams
  - Dynamic diagrams
  - Deployment diagrams
- etc

I do not see this, the diagrams are in the order
#Container-002
#SystemContext-001
#Container-001Cloud

### Steps to reproduce

1. Create a model
2. Create 3 Views: systemContext, container, container
3. View the rendered diagrams

### Screenshot

![image](https://github.com/structurizr/cloud/assets/1202763/0e21c879-dbc4-430d-a4cf-084dfc6b0d1b)

### Code sample

```text
workspace "Commercial" "The IT estate for the Commercial Domain" {

    model {
        user = person "Supplier"
        productLibrary = softwareSystem "Product Library" "App Service" {
            productLibraryApp = container "Web Application" {
                tags "Microsoft Azure - App Services"
                user -> this "Uses"
            }
            mils = container "MILS" "SQL Server Database" "Database" {
                tags "Database" "Microsoft Azure - SQL Server"
                productLibraryApp -> this "reads"
            }
            productIndex = container "Product Index" "Azure Cognitive Search" "Database" {
                tags "Database" "Microsoft Azure - Cognitive Search"
                productLibraryApp -> this "reads"
            }
            productEvents = container "Product Events" "Web Job" {
                tags "Microsoft Azure - Web Jobs"
                this -> mils "listens to CDC events"
                this -> productIndex "updates"
            }
        }
        blackBox = softwareSystem "Blackbox" {
            api = container "API" {
                productLibraryApp -> this "gets product data"
            }
        }
    }
    
    views {
       
        systemContext productLibrary {
            include *
            autolayout lr
        }
        
        container productLibrary {
            include *
        }

        container blackBox {
            include *
            autolayout lr
        }
        
        styles {
            element "Database" {
                shape cylinder
            }
            
        }
        
        themes default https://static.structurizr.com/themes/microsoft-azure-2023.01.24/icons.json
    }

}
```

### Configuration

I'm using the free cloud (SaaS) based software

### Severity

Minor

### Priority

Low

### Resolution

I have no budget and there's no rush, please fix this for free

### More information

I am currently evaluating this and trying to get others on board so I would like the first diagrams they see to be the high level ones or they will get confused.

**Comment by simonbrowndotje** [comment]
At a quick glance, this looks like it's working as described in the docs. You haven't included a full code sample, so it's not reproducible unfortunately.

**Comment by JasonBSteele** [comment]
@simonbrowndotje , 

Thanks for getting back to me so quickly. I have update the OP to include the full code.

I must have misunderstood the docs though because I would have expected the System Context to come before a Container, but as the screenshot shows, this is not the case.

**Comment by simonbrowndotje** [comment]
Thanks. Yes, this looks as expected.

> By default, diagrams are first sorted by scope (unscoped, followed by software systems by name), and then by diagram type

You don't have any unscoped diagrams, so we can ignore that. The software systems sorted by name are:

- `Blackbox`
- `Product Library`

So first you see the diagrams for Blackbox, of which there's only one:

- `Container-002`

Followed by the diagrams for `Product Library`, of which there are two, so they are sorted by type as per the docs:

- `SystemContext-001`
- `Container-001`

**Comment by JasonBSteele** [comment]
Ok, thanks for taking the time for the explanation. I can see now that my expectation for the second SystemContent to be first is wrong because it is from the second system
