### ISSUE TITLE
Need a way to include my interactive C4 model diagrams in my powerpoint presentation 

### ISSUE THREAD

**Issue by amoljoshi10** [structurizr/cloud#2]
@simonbrowndotje   I need to include interactive diagrams in my RFP (PreSales)  PowerPoint presentation for SystemContext,Container and Component  . So I used Stricturizr Cloud Service and tried Export to SVG and Png but these will download individual image files (not interactive)and hence I cannot show same in my PowerPoint presentation interactively so that I can zoom in and zoom out as I can do on browser Strcuturizr DSL editor in cloud service. So I tried   Cloud Service 's  "Export diagrams to an offline HTML page" option and I get very good offline HTML page . And then I have included that offline Html page in my PowerPoint presentation as hyperlink by giving good description to hyperlink.(please see attached screenshot for how it looks like in ppt after and adding as link) . So that I can demo it to my audience by clicking on this link in powerpoint and show offline HTMML page. So  the only Is that the only way to include my C4 interactive diagram in powerpoint? Or is there any other better way?
![PPTScrrenshot](https://user-images.githubusercontent.com/89700319/191293538-b9123ad5-9f24-48c6-afc1-091a1c4e7d94.JPG)

**Comment by amoljoshi10** [comment]
Thanks a lot @simonbrowndotje  for your comments and quick response.  Internet connection is not a problem . I used offline Html page for interactivity like in order to zoom in and zoom out  to various levels in diagram as SVG and PNG file don't  give me those options . It will be just static image file .
So just wanted to know , do you  mean I should  prefer to use cloud service and show these diagrams from Strcuturizr cloud service directly while giving demo of my Presales RFP i.e. proposal?

Or Is there any other way to show these C4 diagrams interactively i.e.  by zoom in and zoom out at various levels?

Can you please let me know how you normally prefer to demo these C4 diagrams to client or various audience s interactively i.e. z by zoom in and zoom out at various levels?

**Comment by simonbrowndotje** [comment]
If you need an interactive diagram presentation, I would use the cloud service in a full-screen web browser, in conjunction with the presentation mode -> https://structurizr.com/help/presentation-mode

**Comment by amoljoshi10** [comment]
Thanks a lot @simonbrowndotje  . I just checked that option you mentioned . It 's awesome.
