### ISSUE TITLE
Cloud Service not showing animation when using include * animation

### ISSUE THREAD

**Issue by amoljoshi10** [structurizr/cloud#3]
@simonbrowndotje  I was looking at example of structurizr dsl at https://structurizr.com/dsl?example=big-bank-plc
 I have a question on usage of below lines where include * animation is written 
And inside that you have added softwaresystem and person model names  defined earlier i.e. internetBankingSystem,email,customer etc.

When I tried this on Structurizr DSL editor in Cloud service and when I checked C4 diagram , it is not showing any animation.

Please find attached screenshot of same where it is not showing any animation.

**What exactly include * animation do?
As when I used Strcuturizr DSL in Cloud Service it is not showing any animation effect.**

**Can you please help me understand the usage of this include * animation and how it works ? Am I missing anything?**

systemcontext internetBankingSystem "SystemContext" {
            **include *
            animation {
                internetBankingSystem
                customer
                mainframe
                email
            }**
            autoLayout
        }

<img width="960" alt="NotSHowingAnimation" src="https://user-images.githubusercontent.com/89700319/191509083-d52be30d-4c2e-4fe9-b2cd-a5c5908e6d46.png">

**Comment by simonbrowndotje** [comment]
The documentation for animation can be found at the following locations:

- Feature overview -> https://structurizr.com/help/animation
- DSL support -> https://github.com/structurizr/dsl/blob/master/docs/language-reference.md#animation

**Comment by amoljoshi10** [comment]
@simonbrowndotje  thanks for your comments. I have gone through this but what I observed is that as shown here https://structurizr.com/help/animation the animation is not happening for below where I applied animation in internetBankingSystem,customer,mainframe and email.

The example I referred it from https://structurizr.com/dsl?example=big-bank-plc.
The same code snippet you will find in this example.

But animation effect I am not getting in diagram.

Can you please help me here.


systemcontext internetBankingSystem "SystemContext" {
include *
animation {
internetBankingSystem
customer
mainframe
email
}
autoLayout
}

**Comment by simonbrowndotje** [comment]
Please attach a screenshot of your web browser.

**Comment by amoljoshi10** [comment]
Sure please find attached screenshot of my Google Chrome Browser in Presentation mode here 
<img width="960" alt="NotSHowingAnimation" src="https://user-images.githubusercontent.com/89700319/191773625-4bbf10e0-a7bc-41f9-b127-2b76b0e1e649.png">

**Comment by simonbrowndotje** [comment]
If you're in presentation mode, you'll need to use the keyboard shortcuts (`,` and `.`) to step through the animation ... assuming that you can see the animation when you are not in presentation mode, of course.

**Comment by simonbrowndotje** [comment]
This is the correct behaviour - the animation is not automatic unless you press the "play" button. Keep pressing the `.` key to progress through the animation (`.` is step forwards; `,` is step backwards). See https://structurizr.com/help/keyboard-shortcuts for more.

<img width="563" alt="Screenshot 2022-09-22 at 16 31 29" src="https://user-images.githubusercontent.com/1009874/191789638-ab14c84d-fad9-459a-bacb-2b0e86dc72c3.png">

**Comment by amoljoshi10** [comment]
Ok Got it !!! I thought it is during initial load. Thanks a lot @simonbrowndotje  for your comments.

**Comment by amoljoshi10** [comment]
Really appreciate for your time @simonbrowndotje  .And I find  structurizr  a great way to communicate architecture to different audiances.
I am learning a great way to communicate my architecture with the Strcuturizr. 

**Can you please suggest any reference if I have want to draw my architecture using C4 Model using Structurizr of my existing .Net or .Net Core Web applications large distributed  application. It will be really helpful.**

Thanks in Advance
