### ISSUE TITLE
Structurizr DSL (cloud service or Lite) of my existing .Net  And Diagram as a code and Diagram as a text 

### ISSUE THREAD

**Issue by amoljoshi10** [structurizr/cloud#4]
@simonbrowndotje  I find structurizr a great way to communicate architecture to different audiences.
I am learning a awesome tool to communicate my architecture with the Strcuturizr . I find this tool and Diagram as a Code 2.0 concept a way better as compared to other tools in market. So first of all thanks a lot for providing such a magnificent tool. 

Really appreciate if would provide your comments on below 2 points
**1.Can you please suggest any reference if I have want to draw my architecture using C4 Model using Structurizr DSL (cloud service or Lite) of my existing .Net or .Net Core Web applications large distributed application. It will be really helpful.**

**2.And also one more question can you please help me to understand what is the difference between Diagram as a code and Diagram as a text.**

Thanks in Advance

**Comment by simonbrowndotje** [comment]
Thanks, I'm glad that you like it. For general questions and discussion though, please join the Slack group (invite link at https://structurizr.com/help/support) ... I'm closing this issue as it's unrelated to the cloud service.

**Comment by amoljoshi10** [comment]
Thanks a lot for an update @simonbrowndotje . I have just joined slack group and posted  these general questions over there.
