### ISSUE TITLE
Error Enabling Client-Side Encryption

### ISSUE THREAD

**Issue by manderson202** [structurizr/cloud#6]
Hello, we have a paid cloud subscription and I have uploaded files to my workspace. I am now trying to enable client-side encryption on the workspace. After first try, it did not appear to be working and so I tried again and found the following error in the console:
```
Uncaught TypeError: Cannot read properties of undefined (reading 'cloneWorkspaceAndRemoveUnnecessaryElements')
    at putWorkspaceViaApi (settings:154:47)
    at Structurizr.saveWorkspace (settings:150:9)
    at addClientSideEncryption (settings:540:25)
    at HTMLButtonElement.onclick (settings:377:115)
```

Is there anything else required to enable this configuration that I may be missing?

**Comment by simonbrowndotje** [comment]
I've just tried this myself on a couple of workspaces, and everything seems to be okay. Could you perhaps try to clear the web browser cache and try again, or try another web browser?

**Comment by manderson202** [comment]
Thanks for the response! I just tried with a clean session in both Chrome and Firefox and I'm still getting the same error. It appears that `Structurizr.workspace` is undefined... Interestingly, it is defined when looking at the workspace summary view but is no longer defined after clicking on "Settings".

**Comment by simonbrowndotje** [comment]
This should be fixed now ... it turns out that the workspace settings page wasn't working properly when users were a workspace admin, which I'm assuming was the problem here too.

**Comment by manderson202** [comment]
Yep, I'm a workspace admin. Just gave it another try and it's working now. Thanks so much for the quick turnaround!
